### ISSUE TITLE
Mouse issue fix

### ISSUE THREAD

**Issue by samdisk11** [DarDarDoor/Wineorc#1]
You do know you can fix the mouse issues by using wine-staging branch as they have implemented mouse fixes for roblox recently.

**Comment by orangessssssss** [comment]
It already states this, "The latest wine (obv, preferably wine-staging)"

**Comment by DarDarDoor** [comment]
i'm gonna leave this issue open for the time being, as this is currently impossible to test with itteblox currently being closed.
also, i'm not sure if those fixes apply to old clients aswell.

**Comment by DarDarDoor** [comment]
the issue seems to be fixed with the latest wine-staging and itteblox. this is probably due to itteblox changing to a 2016e client though. finally, i'm closing this.
